---
config_file: configs/basic.yaml
retriever_name_or_path: facebook/contriever-msmarco
generator_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct
attn_implementation: flash_attention_2
train_file: /home/dju/datasets/qampari/train_data.jsonl
corpus_file: /home/dju/datasets/qampari/wikipedia_chunks/chunks_v5
retrieval_file: /home/dju/datasets/qampari/train_data_bm25-top100.run
dataloader_num_workers: 16
learning_rate: 0.001
lr_scheduler_type: linear
warmup_ratio: 0.1
weight_decay: 0.
report_to: wandb
wandb_project: retrisound-debug
output_dir: /ivi/ilps/personal/dju/checkpoints/adarag_7B
num_train_epochs: 10
save_steps: 1000
logging_steps: 1
total_episodes: 10000
num_ppo_epochs: 10
n_contexts: 10
n_max_candidates: 30
depth: 30
n_max_segments: 5
num_steps: 10
low_cpu_mem_usage: True
reward_function: likelihood
